name: Slim

on:
  push:
    branches:
      - main

jobs:
  slim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Slim
      run: |
        curl https://get.slim.ai | bash
        export PATH=$PATH:/home/runner/.slim/bin/
      
    - name: Build and optimize Docker image with Slim
      run: |
        slim build my-image:latest --entrypoint="my-app start" --http-probe-cmd="my-app healthcheck" --continue-after="my-app test"
      
    - name: Configure Docker CLI
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.io/my-dockerhub-username/my-image:latest
